### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by wei292224644** [Smithsonian/dpo-cook#23]
I cannot find .env file  in "source/client" folder  when i run "npm run build-client".

"source/client/webpack.config.js"
![image](https://user-images.githubusercontent.com/16398073/78697991-356fc880-7934-11ea-930e-494ee11d853c.png)

![image](https://user-images.githubusercontent.com/16398073/78697349-410ebf80-7933-11ea-99b6-ea214b739d02.png)

".gitignore"
![image](https://user-images.githubusercontent.com/16398073/78699016-c6936f00-7935-11ea-8c1b-1445c13f4e1e.png)

**Comment by gjcope** [comment]
.env.template file has been added and docs updated. You will need to copy/rename and set appropriate for your environment.
