### ISSUE TITLE
Tools for Cook

### ISSUE THREAD

**Issue by pisanom** [Smithsonian/dpo-cook#35]
Hi I was wondering if it would be possible to upload the tools that are used in cook since it seems that some of them are not available

**Comment by gjcope** [comment]
Hi @pisanom - is there a specific tool you are looking for? Most of them are listed on this page: https://smithsonian.github.io/dpo-cook/docs/getting-started/ with links to where to get them and recommended versions.

**Comment by pisanom** [comment]
Hi @gjcope the packages I was looking for was RapidCompact, and modified meshlab server. The other ones I was able to install but those two I could not find an installer for Rapid Compact and the modified meshlab server I was having issues compiling. An exe file would be greatly appreciated for both.

Best,
pisanom

**Comment by lanxinger** [comment]
@pisanom rapid compact is a paid service and doesn’t provide this tool for free. You can contact them but it’s not open source or freeware. https://rapidcompact.com/

Meshlab server is deprecated. Meshlab now has a python library that replaces what meshlab server used to do but you can still find archived versions on their GitHub.

**Comment by pisanom** [comment]
@lanxinger I kind of figured that rapid compacts tool was not free anymore.

As for MeshLab I am referencing the one in the documentation as I am aware MeshLab server was depreciated a while back

In order to enable mesh statistics, you need to install a modified meshlab server version from https://github.com/framefactory/meshlab
An precompiled binary is available on the Smithsonian internal digitization drive
Recommended version with Cook: 2019.12, 2019-12-02

I was having issues compiling that version as as it says that there is a precompiled binary available on the Smithsonian internal digitization drive i was wondering if they would not mind sharing that with GitHub incase others like myself are having issues compiling

**Comment by gjcope** [comment]
@pisanom I can check on the binary but ideally you would log your issue on that project to resolve the compiling issues.

**Comment by framefactory** [comment]
@pisanom I added a release of the custom Meshlab version including the binary you need with the Cook. You can find it here: https://github.com/framefactory/meshlab/releases/tag/v1.0.0-si

Just download the zip file `MeshlabMini_2019-12-02_release.zip` and unpack it. Then in `tools.json` point to the corresponding folder.

**Comment by gjcope** [comment]
Thanks @framefactory !

**Comment by pisanom** [comment]
@framefactory and @gjcope thank you for all your help
