### ISSUE TITLE
version of RapidCompact

### ISSUE THREAD

**Issue by fhorn3d** [Smithsonian/dpo-cook#45]
Which version of RapidCompact do you actually use for cook?
As far as I know is the recommended 1.6.0 v still no longer supported by the new token system by DGG.
Thank you.

**Comment by gjcope** [comment]
Thanks for the reminder @fhorn3d . We need to update a number of our software versions but haven't had the cycles. I've tested RapidCompact CLI 4.2.1 and it seems to work fine so I've updated the version in the documentation.
