### ISSUE TITLE
problem with ImageMagick

### ISSUE THREAD

**Issue by fhorn3d** [Smithsonian/dpo-cook#46]
I have a problem getting ImageMagick work.

Maybe it is an problem of the correct path:
in the tools.json is the correct path "D:\voyager_cook\Tools\ImageMagick-7.0.8-Q16\",
but in the log file (see below) is wirtten "D:\voyager_cook\ImageMagick\ImageMagick-7.0.8-Q16\"
Where comes the incorrect path from?

eg.
2021-08-20 16:10:31 INFO  Task 'ConvertImage' started
GET /clients/6867a59e-0ec5-411d-a93e-4f8cd9098823/jobs/00277651-d4d0-becb-b9c9-d110cc23eb54 200 437 - 0.741 ms
2021-08-20 16:10:32 DEBUG Task 'ImageMagick' convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/699.
2021-08-20 16:10:32 DEBUG Task 'ImageMagick'
convert: UnableToOpenModuleFile 'D:\voyager_cook\ImageMagick\ImageMagick-7.0.8-Q16\modules\coders\IM_MOD_RL_PNG_.dll': No such file or directory @ warning/module.c/GetMagickModulePath/675.
2021-08-20 16:10:32 DEBUG Task 'ImageMagick'

What can I do?
Thanks.

**Comment by gjcope** [comment]
Hi @fhorn3d can you attach your tools.json file?

**Comment by fhorn3d** [comment]
tools.json

```json
{
  "FBX2glTF": {
    "executable": "D:\\voyager_cook\\Tools\\FBX2glTF-windows-x64.exe",
    "version": "2.0",
    "maxInstances": 1,
    "timeout": 60 // 1 minute
  },
  "ImageMagick": {
    "executable": "D:\\voyager_cook\\Tools\\ImageMagick-7.0.8-Q16\\magick.exe",
    "version": "7.0.8",
    "maxInstances": 1,
    "timeout": 600 // 10 minutes
  },
  "InstantMeshes": {
    "executable": "D:\\voyager_cook\\Tools\\Instant Meshes.exe",
    "version": "1.0",
    "maxInstances": 1,
    "timeout": 900 // 15 minutes
  },
  "MeshSmith": {
    "executable": "D:\\voyager_cook\\Tools\\MeshSmith\\MeshSmith.exe",
    "version": "v0.6.4, 2019-05-04",
    "maxInstances": 3,
    "timeout": 600 // 10 minutes
  },
  "Meshfix": {
    "executable": "D:\\voyager_cook\\Tools\\MeshFix.exe",
    "version": "v2.1",
    "maxInstances": 1,
    "timeout": 600 // 10 minutes
  },
  "Meshlab": {
    "executable": "D:\\voyager_cook\\Tools\\MeshlabMini\\meshlabserver.exe",
    "version": "v2019.5, 2019-05-02",
    "maxInstances": 3,
    "timeout": 1800 // 30 minutes
  },
  "RapidCompact": {
    "executable": "D:\\voyager_cook\\Tools\\RapidCompact\\rpdx.exe",
    "version": "1.6",
    "maxInstances": 3,
    "timeout": 900 // 15 minutes
  },
  "RizomUV": {
    "executable": "D:\\voyager_cook\\Tools\\Rizom Lab\\RizomUV VS RS 2018.0\\rizomuv.exe",
    "version": "RizomUV_VSRS.2018.0.85.g41754c4.master",
    "maxInstances": 2,
    "timeout": 1800 // 30 minutes
  },
  "XNormal": {
    "executable": "D:\\voyager_cook\\Tools\\xNormal\\3.19.3\\x64\\xNormal.exe",
    "version": "3.19.3.39669",
    "maxInstances": 1,
    "timeout": 2700 // 45 minutes
  }
}
```

**Comment by fhorn3d** [comment]
I found the problem: it was it was due to an old installation path who was missleading.

Thank you.

**Comment by gjcope** [comment]
Glad you figured it out! Let me know if you have any other issues.
