### ISSUE TITLE
How to remote Cook

### ISSUE THREAD

**Issue by fhorn3d** [Smithsonian/dpo-cook#49]
Hi there,
what do I have to do to run cook via remote tools,
could I do that with the Web API on SwaggerHub ( https://app.swaggerhub.com/apis/Frame-Factory/Cook/1.0.0 )?

The other option the Remote CLI there is an error report while opening the link:
( https://smithsonian.github.io/dpo-cook/docs/cli/ )

Could you please give some informations on how to remote cook?
Thank you.

Best,
Felix

**Comment by gjcope** [comment]
Hi @fhorn3d ,

There are 3 ways to work with Cook remotely.

- You can use the web UI by spinning up the server as described here (https://smithsonian.github.io/dpo-cook/docs/getting-started/) and then accessing the server via browser at whatever port you defined in the configuration.
- As you already mentioned, you can also use the API endpoints described here (https://app.swaggerhub.com/apis/Frame-Factory/Cook/1.0.0)
- The CLI is here (https://github.com/Smithsonian/dpo-cook-cli). Thanks for pointing out the broken link!

-Jamie

**Comment by fhorn3d** [comment]
Thank you, Jamie!
